import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="dark">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col bg-gradient-to-b from-[#0d0d0f] to-[#18181b]`}
        >
          <header className="sticky top-0 z-50 shadow-lg border-b border-[#27272a] bg-gradient-to-r from-[#18181b] to-[#0d0d0f] backdrop-blur">
            <Header />
          </header>

          <main className="flex-1 w-full max-w-6xl mx-auto p-6">
            <div className="card">{children}</div>
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
